"""PostgreSQL 対応（utils/db.py）のテスト。

- to_pg_ddl(): SQLite DDL → PostgreSQL DDL の変換正しさ
- _prepare(): ? プレースホルダ → $n 変換
- ライブ PG 結合テスト（環境変数 CLUB_TEST_PG_DSN がある場合のみ実行）

実行: venv/bin/python -m pytest tests/
ライブ PG: CLUB_TEST_PG_DSN=postgresql://user:pass@host:5432/db pytest tests/test_db_postgres.py
"""
import asyncio
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

import pytest  # noqa: E402

from utils.db import SCHEMA_VERSION, TABLE_DDL, TABLE_DDL_PG, Database, to_pg_ddl  # noqa: E402

PG_DSN = os.getenv("CLUB_TEST_PG_DSN")

G1 = 100000000000000001
G2 = 200000000000000002


def run(coro):
    return asyncio.run(coro)


# ---------------------------------------------------------------------
# DDL 変換（サーバー不要）
# ---------------------------------------------------------------------
def test_to_pg_ddl_autoincrement_and_guild_id():
    for name, ddl in TABLE_DDL_PG.items():
        # SQLite 固有構文が残っていないこと
        assert "AUTOINCREMENT" not in ddl, name
        assert "datetime('now', 'localtime')" not in ddl, name
        assert "guild_id INTEGER" not in ddl, name
        # PG 側の型が入っていること
        assert "IF NOT EXISTS" in ddl, name
    # IDENTITY 化されること
    assert "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY" in TABLE_DDL_PG["tasks"]
    # ギルド台帳の PK も BIGINT
    assert "guild_id      BIGINT PRIMARY KEY" in TABLE_DDL_PG["guilds"]
    # 時刻関数の変換
    assert "to_char(CURRENT_TIMESTAMP" in TABLE_DDL_PG["settings"]


def test_to_pg_ddl_preserves_constraints():
    ddl = to_pg_ddl(TABLE_DDL["schedule_votes"])
    assert "UNIQUE (guild_id, option_id, user_id)" in ddl
    assert "ON DELETE CASCADE" in ddl
    assert "CHECK (guild_id >= 0)" in ddl


# ---------------------------------------------------------------------
# プレースホルダ変換（サーバー不要）
# ---------------------------------------------------------------------
def test_prepare_converts_placeholders():
    db = Database("./dummy.db", database_url="postgresql://u:p@localhost/d")
    stmt, args = db._prepare(
        "SELECT * FROM tasks WHERE guild_id = ? AND status = ? AND local_task_id = ?",
        (1, "open", 42))
    assert stmt == ("SELECT * FROM tasks WHERE guild_id = $1"
                    " AND status = $2 AND local_task_id = $3")
    assert args == [1, "open", 42]


def test_prepare_sqlite_passthrough():
    db = Database("./dummy.db")
    stmt, args = db._prepare("SELECT * FROM tasks WHERE guild_id = ?", (1,))
    assert stmt == "SELECT * FROM tasks WHERE guild_id = ?"
    assert args == [1]


def test_driver_name():
    assert Database("./x.db").driver_name == "SQLite"
    assert Database("./x.db", database_url="postgresql://u:p@h/d").driver_name == "PostgreSQL"


# ---------------------------------------------------------------------
# ライブ PG 結合テスト（CLUB_TEST_PG_DSN がある場合のみ）
# ---------------------------------------------------------------------
pytestmark_live = pytest.mark.skipif(not PG_DSN, reason="CLUB_TEST_PG_DSN 未設定")


@pytestmark_live
def test_pg_live_schema_and_crud():
    async def _main():
        from repositories.member_repository import MemberRepository
        from repositories.task_repository import TaskRepository
        db = Database("./unused.db", database_url=PG_DSN)
        await db.connect()
        try:
            # スキーマバージョン
            row = await db.fetchone("SELECT version FROM schema_meta WHERE id = 1")
            assert row["version"] == SCHEMA_VERSION
            # CRUD + lastrowid
            tasks = TaskRepository(db)
            t1 = await tasks.create_task(G1, "PGタスク1", created_by="u1")
            t2 = await tasks.create_task(G1, "PGタスク2", created_by="u1")
            assert t1 and t2 and t2 > t1
            assert (await tasks.get_task(G1, t1))["title"] == "PGタスク1"
            assert await tasks.get_task(G2, t1) is None  # ギルド分離
            # upsert（ON CONFLICT）
            members = MemberRepository(db)
            await members.upsert_team(G1, "wing", "翼")
            await members.upsert_team(G1, "wing", "翼改")
            assert (await members.get_team(G1, "wing"))["team_name"] == "翼改"
            # rowcount
            assert await members.deactivate_team(G1, "wing") is True
            assert await members.deactivate_team(G1, "wing") is False
        finally:
            # 後片付け（テストデータ削除）
            await db.execute("DELETE FROM tasks WHERE guild_id IN (?, ?)", (G1, G2))
            await db.execute("DELETE FROM teams WHERE guild_id IN (?, ?)", (G1, G2))
            await db.close()
    run(_main())


@pytestmark_live
def test_pg_live_sequence_fix():
    """明示 ID 挿入後もシーケンスが修復され PK 衝突しないこと。"""
    async def _main():
        db = Database("./unused.db", database_url=PG_DSN)
        await db.connect()
        try:
            # 明示 ID で大きな値を挿入（SQLite 移行を再現）
            await db.execute(
                "INSERT INTO tasks (local_task_id, guild_id, title, status,"
                " created_by, created_at) VALUES (900001, ?, '明示ID', 'open', 'u1', '2026-01-01')",
                (G1,))
            # シーケンス修復（connect 時にも走るが明示的に再実行）
            await db._pg_fix_sequences()
            # 次の自動採番が衝突しない
            cur = await db.execute(
                "INSERT INTO tasks (guild_id, title, status, created_by, created_at)"
                " VALUES (?, '自動採番', 'open', 'u1', '2026-01-01')", (G1,))
            assert cur.lastrowid > 900001
        finally:
            await db.execute("DELETE FROM tasks WHERE guild_id IN (?, ?)", (G1, G2))
            await db.close()
    run(_main())


if __name__ == "__main__":
    test_to_pg_ddl_autoincrement_and_guild_id()
    print("test_to_pg_ddl_autoincrement_and_guild_id: OK")
    test_to_pg_ddl_preserves_constraints()
    print("test_to_pg_ddl_preserves_constraints: OK")
    test_prepare_converts_placeholders()
    print("test_prepare_converts_placeholders: OK")
    test_prepare_sqlite_passthrough()
    print("test_prepare_sqlite_passthrough: OK")
    test_driver_name()
    print("test_driver_name: OK")
    if PG_DSN:
        test_pg_live_schema_and_crud()
        print("test_pg_live_schema_and_crud: OK")
        test_pg_live_sequence_fix()
        print("test_pg_live_sequence_fix: OK")
    else:
        print("ライブ PG テストは CLUB_TEST_PG_DSN 未設定のためスキップ")
    print("全テスト成功")
