"""PostgreSQL 対応（utils/db.py）のテスト。

- to_pg_ddl(): SQLite DDL → PostgreSQL DDL の変換正しさ
- _prepare(): ? プレースホルダ → $n 変換
- ライブ PG 結合テスト（環境変数 CLUB_TEST_PG_DSN がある場合のみ実行）

実行: venv/bin/python -m pytest tests/
ライブ PG: CLUB_TEST_PG_DSN=postgresql://user:pass@host:5432/db pytest tests/test_db_postgres.py
"""
import asyncio
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

import pytest  # noqa: E402

from utils.db import (  # noqa: E402
    INDEX_DDL, POSTGRES_VIEW_DDL, SCHEMA_META_DDL, SCHEMA_VERSION,
    SQLITE_VIEW_DDL, TABLE_DDL, TABLE_DDL_PG, Database, to_pg_ddl,
)

G1 = 100000000000000001
G2 = 200000000000000002


def run(coro):
    return asyncio.run(coro)


async def _current_db_name(dsn: str) -> str:
    """接続先のデータベース名を返す（スキーマ作成より前の安全確認用）。"""
    import asyncpg
    con = await asyncpg.connect(dsn)
    try:
        return await con.fetchval("SELECT current_database()")
    finally:
        await con.close()


def _guarded_dsn() -> str:
    """CLUB_TEST_PG_DSN がテスト専用 DB を指す場合だけ返す。

    本番の clubdb 等を誤って初期化・変更しないよう、接続先の
    データベース名に "test" を含む場合に限定する
    （スキーマ作成より前にチェックする）。
    """
    dsn = os.getenv("CLUB_TEST_PG_DSN")
    if not dsn:
        pytest.skip("CLUB_TEST_PG_DSN 未設定（テスト専用 DB の DSN を指定してください）")
    db_name = run(_current_db_name(dsn))
    if "test" not in db_name.lower():
        pytest.skip(
            "安全のためライブテストはテスト専用 DB でのみ実行します"
            f"（接続先: {db_name}。clubbot_test など test を含む DB を指定してください）")
    return dsn


# ---------------------------------------------------------------------
# DDL 変換（サーバー不要）
# ---------------------------------------------------------------------
def test_to_pg_ddl_autoincrement_and_guild_id():
    for name, ddl in TABLE_DDL_PG.items():
        # SQLite 固有構文が残っていないこと
        assert "AUTOINCREMENT" not in ddl, name
        assert "datetime('now', 'localtime')" not in ddl, name
        assert "guild_id INTEGER" not in ddl, name
        # PG 側の型が入っていること
        assert "IF NOT EXISTS" in ddl, name
    # IDENTITY 化されること
    assert "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY" in TABLE_DDL_PG["tasks"]
    # ギルド台帳の PK も BIGINT
    assert "guild_id      BIGINT PRIMARY KEY" in TABLE_DDL_PG["guilds"]
    # 時刻関数の変換
    assert "to_char(CURRENT_TIMESTAMP" in TABLE_DDL_PG["settings"]


def test_to_pg_ddl_preserves_constraints():
    ddl = to_pg_ddl(TABLE_DDL["schedule_votes"])
    assert "UNIQUE (guild_id, option_id, user_id)" in ddl
    assert "ON DELETE CASCADE" in ddl
    assert "CHECK (guild_id >= 0)" in ddl


def test_view_ddl_separation():
    """ビュー DDL は SQLite / PostgreSQL で共用せず分離されていること。

    回帰テスト: PostgreSQL は CREATE VIEW IF NOT EXISTS をサポートしない
    （syntax error at or near "NOT"）、SQLite は CREATE OR REPLACE VIEW を
    サポートしない。両ドライバでビュー初期化が冪等である定義になっているか
    確認する。
    """
    views = ("v_todoist_status", "v_attendance", "v_team_summary")

    # PostgreSQL 用: CREATE OR REPLACE VIEW（冪等）。IF NOT EXISTS は渡さない
    assert "IF NOT EXISTS" not in POSTGRES_VIEW_DDL
    for v in views:
        assert f"CREATE OR REPLACE VIEW {v}" in POSTGRES_VIEW_DDL

    # SQLite 用: DROP VIEW IF EXISTS + CREATE VIEW の再作成方式（冪等）。
    # SQLite 非対応の CREATE OR REPLACE VIEW は使わない
    assert "CREATE OR REPLACE VIEW" not in SQLITE_VIEW_DDL
    assert "CREATE VIEW IF NOT EXISTS" not in SQLITE_VIEW_DDL
    for v in views:
        assert f"DROP VIEW IF EXISTS {v}" in SQLITE_VIEW_DDL
        assert f"CREATE VIEW {v}" in SQLITE_VIEW_DDL

    # ビュー本体（SELECT 部）は両者で同一
    for body_sql in ("FROM schedule_votes", "GROUP BY t.guild_id, t.team_key, t.team_name"):
        assert body_sql in POSTGRES_VIEW_DDL
        assert body_sql in SQLITE_VIEW_DDL


def test_sqlite_view_init_idempotent():
    """SQLite でビュー初期化（DROP+CREATE）を2回実行しても冪等であること。"""
    import tempfile

    async def _main():
        fd, path = tempfile.mkstemp(suffix=".db")
        os.close(fd)
        os.unlink(path)
        db = Database(path)
        await db.connect()
        try:
            # connect 時に1回作成済み。もう1回実行しても壊れないこと
            await db._executescript(SQLITE_VIEW_DDL)
            for v in ("v_todoist_status", "v_attendance", "v_team_summary"):
                rows = await db.fetchall(
                    "SELECT name FROM sqlite_master WHERE type='view' AND name = ?",
                    (v,))
                assert rows, f"{v} がありません"
            # ビューが実際に読めること
            await db.fetchall("SELECT * FROM v_attendance LIMIT 0")
            await db.fetchall("SELECT * FROM v_team_summary LIMIT 0")
        finally:
            await db.close()
    run(_main())


def test_pg_ddl_no_unsupported_constructs():
    """PostgreSQL へ送信する全 DDL（テーブル・メタ・インデックス・ビュー）に
    PG 非対応の構文が残っていないことを検証する。"""
    all_pg_ddl = list(TABLE_DDL_PG.values()) + [SCHEMA_META_DDL, INDEX_DDL,
                                                POSTGRES_VIEW_DDL]
    for ddl in all_pg_ddl:
        assert "AUTOINCREMENT" not in ddl
        assert "datetime(" not in ddl
        # CREATE VIEW IF NOT EXISTS は PG 非対応（TABLE/INDEX の IF NOT EXISTS は有効）
        assert "CREATE VIEW IF NOT EXISTS" not in ddl


# ---------------------------------------------------------------------
# プレースホルダ変換（サーバー不要）
# ---------------------------------------------------------------------
def test_prepare_converts_placeholders():
    db = Database("./dummy.db", database_url="postgresql://u:p@localhost/d")
    stmt, args = db._prepare(
        "SELECT * FROM tasks WHERE guild_id = ? AND status = ? AND local_task_id = ?",
        (1, "open", 42))
    assert stmt == ("SELECT * FROM tasks WHERE guild_id = $1"
                    " AND status = $2 AND local_task_id = $3")
    assert args == [1, "open", 42]


def test_prepare_sqlite_passthrough():
    db = Database("./dummy.db")
    stmt, args = db._prepare("SELECT * FROM tasks WHERE guild_id = ?", (1,))
    assert stmt == "SELECT * FROM tasks WHERE guild_id = ?"
    assert args == [1]


def test_driver_name():
    assert Database("./x.db").driver_name == "SQLite"
    assert Database("./x.db", database_url="postgresql://u:p@h/d").driver_name == "PostgreSQL"


# ---------------------------------------------------------------------
# ライブ PG 結合テスト（CLUB_TEST_PG_DSN がテスト専用 DB を指す場合のみ）
# ---------------------------------------------------------------------
def test_pg_live_schema_and_crud():
    dsn = _guarded_dsn()

    async def _main():
        from repositories.member_repository import MemberRepository
        from repositories.task_repository import TaskRepository
        db = Database("./unused.db", database_url=dsn)
        await db.connect()
        try:
            # スキーマバージョン
            row = await db.fetchone("SELECT version FROM schema_meta WHERE id = 1")
            assert row["version"] == SCHEMA_VERSION
            # CRUD + lastrowid
            tasks = TaskRepository(db)
            t1 = await tasks.create_task(G1, "PGタスク1", created_by="u1")
            t2 = await tasks.create_task(G1, "PGタスク2", created_by="u1")
            assert t1 and t2 and t2 > t1
            assert (await tasks.get_task(G1, t1))["title"] == "PGタスク1"
            assert await tasks.get_task(G2, t1) is None  # ギルド分離
            # upsert（ON CONFLICT）
            members = MemberRepository(db)
            await members.upsert_team(G1, "wing", "翼")
            await members.upsert_team(G1, "wing", "翼改")
            assert (await members.get_team(G1, "wing"))["team_name"] == "翼改"
            # rowcount
            assert await members.deactivate_team(G1, "wing") is True
            assert await members.deactivate_team(G1, "wing") is False
            # ビュー初期化の冪等性（CREATE OR REPLACE VIEW を再実行しても壊れない）
            await db._executescript(POSTGRES_VIEW_DDL)
            views = await db.fetchall(
                "SELECT table_name FROM information_schema.views"
                " WHERE table_name IN ('v_todoist_status', 'v_attendance', 'v_team_summary')")
            assert len(views) == 3
        finally:
            # 後片付け（テストデータ削除）
            await db.execute("DELETE FROM tasks WHERE guild_id IN (?, ?)", (G1, G2))
            await db.execute("DELETE FROM teams WHERE guild_id IN (?, ?)", (G1, G2))
            await db.close()
    run(_main())


def test_pg_live_sequence_fix():
    """明示 ID 挿入後もシーケンスが修復され PK 衝突しないこと。"""
    dsn = _guarded_dsn()

    async def _main():
        db = Database("./unused.db", database_url=dsn)
        await db.connect()
        try:
            # 明示 ID で大きな値を挿入（SQLite 移行を再現）
            await db.execute(
                "INSERT INTO tasks (local_task_id, guild_id, title, status,"
                " created_by, created_at) VALUES (900001, ?, '明示ID', 'open', 'u1', '2026-01-01')",
                (G1,))
            # シーケンス修復（connect 時にも走るが明示的に再実行）
            await db._pg_fix_sequences()
            # 次の自動採番が衝突しない
            cur = await db.execute(
                "INSERT INTO tasks (guild_id, title, status, created_by, created_at)"
                " VALUES (?, '自動採番', 'open', 'u1', '2026-01-01')", (G1,))
            assert cur.lastrowid > 900001
        finally:
            await db.execute("DELETE FROM tasks WHERE guild_id IN (?, ?)", (G1, G2))
            await db.close()
    run(_main())


if __name__ == "__main__":
    test_to_pg_ddl_autoincrement_and_guild_id()
    print("test_to_pg_ddl_autoincrement_and_guild_id: OK")
    test_to_pg_ddl_preserves_constraints()
    print("test_to_pg_ddl_preserves_constraints: OK")
    test_view_ddl_separation()
    print("test_view_ddl_separation: OK")
    test_sqlite_view_init_idempotent()
    print("test_sqlite_view_init_idempotent: OK")
    test_pg_ddl_no_unsupported_constructs()
    print("test_pg_ddl_no_unsupported_constructs: OK")
    test_prepare_converts_placeholders()
    print("test_prepare_converts_placeholders: OK")
    test_prepare_sqlite_passthrough()
    print("test_prepare_sqlite_passthrough: OK")
    test_driver_name()
    print("test_driver_name: OK")
    if os.getenv("CLUB_TEST_PG_DSN"):
        test_pg_live_schema_and_crud()
        print("test_pg_live_schema_and_crud: OK")
        test_pg_live_sequence_fix()
        print("test_pg_live_sequence_fix: OK")
    else:
        print("ライブ PG テストは CLUB_TEST_PG_DSN 未設定のためスキップ")
    print("全テスト成功")
