"""PostgreSQL 対応（utils/db.py）のテスト。

- to_pg_ddl(): SQLite DDL → PostgreSQL DDL の変換正しさ
- _prepare(): ? プレースホルダ → $n 変換
- ライブ PG 結合テスト（環境変数 CLUB_TEST_PG_DSN がテスト専用 DB を指す場合のみ実行）

実行: venv/bin/python -m pytest tests/
ライブ PG: CLUB_TEST_PG_DSN=postgresql://user:pass@host:5432/clubbot_test pytest tests/test_db_postgres.py
"""

import asyncio
import os
import re
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

import pytest

from utils.db import (
    INDEX_DDL,
    POSTGRES_VIEW_DDL,
    SCHEMA_META_DDL,
    SCHEMA_VERSION,
    SQLITE_VIEW_DDL,
    TABLE_DDL,
    TABLE_DDL_PG,
    Database,
    to_pg_ddl,
)

# 2^31 を超える Discord Snowflake ID（int32 では表現できない）※明白なダミー値
BIG_SNOWFLAKE = 3000000000000000001

G1 = 100000000000000001
G2 = 200000000000000002


def run(coro):
    return asyncio.run(coro)


async def _current_db_name(dsn: str) -> str:
    """接続先のデータベース名を返す（スキーマ作成より前の安全確認用）。"""
    import asyncpg

    con = await asyncpg.connect(dsn)
    try:
        return await con.fetchval("SELECT current_database()")
    finally:
        await con.close()


def _guarded_dsn() -> str:
    """CLUB_TEST_PG_DSN がテスト専用 DB を指す場合だけ返す。

    本番の clubdb 等を誤って初期化・変更しないよう、接続先の
    データベース名に "test" を含む場合に限定する
    （スキーマ作成より前にチェックする）。
    """
    dsn = os.getenv("CLUB_TEST_PG_DSN")
    if not dsn:
        pytest.skip("CLUB_TEST_PG_DSN 未設定（テスト専用 DB の DSN を指定してください）")
    db_name = run(_current_db_name(dsn))
    if "test" not in db_name.lower():
        pytest.skip(
            "安全のためライブテストはテスト専用 DB でのみ実行します"
            f"（接続先: {db_name}。clubbot_test など test を含む DB を指定してください）"
        )
    return dsn


# ---------------------------------------------------------------------
# DDL 変換（サーバー不要）
# ---------------------------------------------------------------------
def test_to_pg_ddl_autoincrement_and_guild_id():
    for name, ddl in TABLE_DDL_PG.items():
        # SQLite 固有構文が残っていないこと
        assert "AUTOINCREMENT" not in ddl, name
        assert "datetime('now', 'localtime')" not in ddl, name
        # guild_id はアライメントに関係なく全て BIGINT であること
        # （回帰: todoist_configs がスペース数の違いで変換漏れしていた）
        assert not re.search(r"guild_id\s+INTEGER", ddl), name
        # PG 側の型が入っていること
        assert "IF NOT EXISTS" in ddl, name
    # IDENTITY 化されること
    assert "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY" in TABLE_DDL_PG["members"]
    # ギルド台帳の PK も BIGINT
    assert re.search(r"guild_id\s+BIGINT PRIMARY KEY", TABLE_DDL_PG["guilds"])
    # todoist_configs の PK も BIGINT（Discord Snowflake は int4 に収まらない）
    assert re.search(r"guild_id\s+BIGINT PRIMARY KEY", TABLE_DDL_PG["todoist_configs"])
    # 時刻関数の変換
    assert "to_char(CURRENT_TIMESTAMP" in TABLE_DDL_PG["settings"]


def test_to_pg_ddl_preserves_constraints():
    ddl = to_pg_ddl(TABLE_DDL["schedule_votes"])
    assert "UNIQUE (guild_id, option_id, user_id)" in ddl
    assert "ON DELETE CASCADE" in ddl
    assert "CHECK (guild_id >= 0)" in ddl


def test_view_ddl_separation():
    """ビュー DDL は SQLite / PostgreSQL で共用せず分離されていること。

    回帰テスト: PostgreSQL は CREATE VIEW IF NOT EXISTS をサポートしない
    （syntax error at or near "NOT"）、SQLite は CREATE OR REPLACE VIEW を
    サポートしない。両ドライバでビュー初期化が冪等である定義になっているか
    確認する。
    """
    views = ("v_todoist_status", "v_attendance", "v_team_summary")

    # PostgreSQL 用: CREATE OR REPLACE VIEW（冪等）。IF NOT EXISTS は渡さない
    assert "IF NOT EXISTS" not in POSTGRES_VIEW_DDL
    for v in views:
        assert f"CREATE OR REPLACE VIEW {v}" in POSTGRES_VIEW_DDL

    # SQLite 用: DROP VIEW IF EXISTS + CREATE VIEW の再作成方式（冪等）。
    # SQLite 非対応の CREATE OR REPLACE VIEW は使わない
    assert "CREATE OR REPLACE VIEW" not in SQLITE_VIEW_DDL
    assert "CREATE VIEW IF NOT EXISTS" not in SQLITE_VIEW_DDL
    for v in views:
        assert f"DROP VIEW IF EXISTS {v}" in SQLITE_VIEW_DDL
        assert f"CREATE VIEW {v}" in SQLITE_VIEW_DDL

    # ビュー本体（SELECT 部）は両者で同一
    for body_sql in ("FROM schedule_votes", "GROUP BY t.guild_id, t.team_key, t.team_name"):
        assert body_sql in POSTGRES_VIEW_DDL
        assert body_sql in SQLITE_VIEW_DDL


def test_sqlite_view_init_idempotent():
    """SQLite でビュー初期化（DROP+CREATE）を2回実行しても冪等であること。"""
    import tempfile

    async def _main():
        fd, path = tempfile.mkstemp(suffix=".db")
        os.close(fd)
        os.unlink(path)
        db = Database(path)
        await db.connect()
        try:
            # connect 時に1回作成済み。もう1回実行しても壊れないこと
            await db._executescript(SQLITE_VIEW_DDL)
            for v in ("v_todoist_status", "v_attendance", "v_team_summary"):
                rows = await db.fetchall(
                    "SELECT name FROM sqlite_master WHERE type='view' AND name = ?", (v,)
                )
                assert rows, f"{v} がありません"
            # ビューが実際に読めること
            await db.fetchall("SELECT * FROM v_attendance LIMIT 0")
            await db.fetchall("SELECT * FROM v_team_summary LIMIT 0")
        finally:
            await db.close()

    run(_main())


def test_pg_ddl_no_unsupported_constructs():
    """PostgreSQL へ送信する全 DDL（テーブル・メタ・インデックス・ビュー）に
    PG 非対応の構文が残っていないことを検証する。"""
    all_pg_ddl = list(TABLE_DDL_PG.values()) + [SCHEMA_META_DDL, INDEX_DDL, POSTGRES_VIEW_DDL]
    for ddl in all_pg_ddl:
        assert "AUTOINCREMENT" not in ddl
        assert "datetime(" not in ddl
        # CREATE VIEW IF NOT EXISTS は PG 非対応（TABLE/INDEX の IF NOT EXISTS は有効）
        assert "CREATE VIEW IF NOT EXISTS" not in ddl


# ---------------------------------------------------------------------
# プレースホルダ変換（サーバー不要）
# ---------------------------------------------------------------------
def test_prepare_converts_placeholders():
    db = Database("./dummy.db", database_url="postgresql://u:p@localhost/d")
    stmt, args = db._prepare(
        "SELECT * FROM members WHERE guild_id = ? AND status = ? AND member_id = ?",
        (1, "active", 42),
    )
    assert stmt == (
        "SELECT * FROM members WHERE guild_id = $1 AND status = $2 AND member_id = $3"
    )
    assert args == [1, "active", 42]


def test_prepare_sqlite_passthrough():
    db = Database("./dummy.db")
    stmt, args = db._prepare("SELECT * FROM members WHERE guild_id = ?", (1,))
    assert stmt == "SELECT * FROM members WHERE guild_id = ?"
    assert args == [1]


def test_driver_name():
    assert Database("./x.db").driver_name == "SQLite"
    assert Database("./x.db", database_url="postgresql://u:p@h/d").driver_name == "PostgreSQL"


def test_pg_indexes_are_created_after_migrations(monkeypatch):
    """インデックス・ビューはマイグレーションの後に作ること。

    CREATE TABLE IF NOT EXISTS は既存テーブルへ列を追加しないため、
    旧バージョンで作られた DB には後から追加した列
    （guilds.purge_after / members.status など）がマイグレーション前には
    存在しない。インデックスを先に作ると
    UndefinedColumnError: column "purge_after" does not exist
    で起動に失敗する（実際に発生した回帰）。
    """
    events: list[str] = []

    class _FakeConnection:
        async def execute(self, sql):  # 実際の DDL 実行はしない
            return None

    class _FakeAcquire:
        async def __aenter__(self):
            return _FakeConnection()

        async def __aexit__(self, *exc):
            return False

    class _FakePool:
        def acquire(self):
            return _FakeAcquire()

        async def close(self):
            return None

    class _FakeAsyncpg:
        @staticmethod
        async def create_pool(**kwargs):
            return _FakePool()

    monkeypatch.setattr("utils.db.asyncpg", _FakeAsyncpg)

    db = Database("./ignored.db", database_url="postgresql://u:p@h/d")

    async def _fake_exec_ddl(con, label, sql):
        events.append(label)

    async def _fake_migrate():
        events.append("migrate")

    async def _fake_fix_sequences():
        events.append("sequences")

    monkeypatch.setattr(db, "_pg_exec_ddl", _fake_exec_ddl)
    monkeypatch.setattr(db, "_migrate_versioned", _fake_migrate)
    monkeypatch.setattr(db, "_pg_fix_sequences", _fake_fix_sequences)

    run(db.connect())

    assert {"migrate", "indexes", "views", "table:guilds"} <= set(events)
    # テーブル作成 → マイグレーション → インデックス/ビュー の順
    assert events.index("table:guilds") < events.index("migrate")
    assert events.index("table:schema_meta") < events.index("migrate")
    assert events.index("migrate") < events.index("indexes")
    assert events.index("migrate") < events.index("views")


def test_index_ddl_columns_exist_in_table_ddl():
    """INDEX_DDL が参照する列は最新スキーマ（TABLE_DDL）に存在すること。"""
    pattern = re.compile(r"CREATE INDEX IF NOT EXISTS \w+\s+ON\s+(\w+)\s*\(([^)]*)\)")
    for table, columns in pattern.findall(INDEX_DDL):
        ddl = TABLE_DDL.get(table)
        assert ddl, f"INDEX_DDL が未知のテーブル {table} を参照している"
        for column in (c.strip() for c in columns.split(",")):
            assert re.search(rf"^\s*{re.escape(column)}\b", ddl, re.MULTILINE), (
                f"{table}.{column} が TABLE_DDL に無い"
            )


# ---------------------------------------------------------------------
# ライブ PG 結合テスト（CLUB_TEST_PG_DSN がテスト専用 DB を指す場合のみ）
# ---------------------------------------------------------------------
def test_pg_live_schema_and_crud():
    dsn = _guarded_dsn()

    async def _main():
        from repositories.layer_session_repository import LayerSessionRepository
        from repositories.member_repository import MemberRepository

        db = Database("./unused.db", database_url=dsn)
        await db.connect()
        try:
            # スキーマバージョン
            row = await db.fetchone("SELECT version FROM schema_meta WHERE id = 1")
            assert row["version"] == SCHEMA_VERSION
            # CRUD + lastrowid
            sessions = LayerSessionRepository(db)
            r1 = await sessions.add_record(G1, "u1", "主桁", "1", "2026-01-01", "2026-01-01", 30)
            r2 = await sessions.add_record(G1, "u1", "主桁", "2", "2026-01-01", "2026-01-01", 40)
            assert r1 and r2 and r2 > r1
            records = await sessions.list_records(G1)
            assert [r["layer_num"] for r in records] == ["1", "2"]
            assert await sessions.list_records(G2) == []  # ギルド分離
            # upsert（ON CONFLICT）
            members = MemberRepository(db)
            await members.upsert_team(G1, "wing", "翼")
            await members.upsert_team(G1, "wing", "翼改")
            assert (await members.get_team(G1, "wing"))["team_name"] == "翼改"
            # rowcount
            assert await members.deactivate_team(G1, "wing") is True
            assert await members.deactivate_team(G1, "wing") is False
            # ビュー初期化の冪等性（CREATE OR REPLACE VIEW を再実行しても壊れない）
            await db._executescript(POSTGRES_VIEW_DDL)
            views = await db.fetchall(
                "SELECT table_name FROM information_schema.views"
                " WHERE table_name IN ('v_todoist_status', 'v_attendance', 'v_team_summary')"
            )
            assert len(views) == 3
        finally:
            # 後片付け（テストデータ削除）
            await db.execute("DELETE FROM layer_records WHERE guild_id IN (?, ?)", (G1, G2))
            await db.execute("DELETE FROM teams WHERE guild_id IN (?, ?)", (G1, G2))
            await db.close()

    run(_main())


def test_pg_live_sequence_fix():
    """明示 ID 挿入後もシーケンスが修復され PK 衝突しないこと。"""
    dsn = _guarded_dsn()

    async def _main():
        db = Database("./unused.db", database_url=dsn)
        await db.connect()
        try:
            # 明示 ID で大きな値を挿入（SQLite 移行を再現）
            await db.execute(
                "INSERT INTO layer_records (record_id, guild_id, user_id, keta, layer_num,"
                " started_at, ended_at, minutes)"
                " VALUES (900001, ?, 'u1', '主桁', '明示ID', '2026-01-01', '2026-01-01', 30)",
                (G1,),
            )
            # シーケンス修復（connect 時にも走るが明示的に再実行）
            await db._pg_fix_sequences()
            # 次の自動採番が衝突しない
            cur = await db.execute(
                "INSERT INTO layer_records (guild_id, user_id, keta, layer_num,"
                " started_at, ended_at, minutes)"
                " VALUES (?, 'u1', '主桁', '自動採番', '2026-01-01', '2026-01-01', 30)",
                (G1,),
            )
            assert cur.lastrowid > 900001
        finally:
            await db.execute("DELETE FROM layer_records WHERE guild_id IN (?, ?)", (G1, G2))
            await db.close()

    run(_main())


def test_pg_live_big_snowflake_crud():
    """2^31 を超える Discord Snowflake ID（guild/user/role/channel）を
    PostgreSQL で INSERT/SELECT/UPDATE/DELETE できること。

    回帰: todoist_configs.guild_id が int4 で作成され、
    DataError: value out of int32 range となっていた。
    """
    dsn = _guarded_dsn()

    async def _main():
        from repositories.layer_session_repository import LayerSessionRepository
        from repositories.member_repository import MemberRepository
        from repositories.todoist_config_repository import TodoistConfigRepository

        big_user = str(BIG_SNOWFLAKE)
        big_role = str(BIG_SNOWFLAKE + 1)
        big_channel = str(BIG_SNOWFLAKE + 2)
        db = Database("./unused.db", database_url=dsn)
        await db.connect()
        try:
            # --- todoist_configs（修正対象の本体）---
            todoist = TodoistConfigRepository(db)
            await todoist.upsert(BIG_SNOWFLAKE, "cipher-x", "proj", "今日やること", "admin")
            cfg = await todoist.get(BIG_SNOWFLAKE)
            assert cfg is not None and cfg["api_token_encrypted"] == "cipher-x"
            # UPDATE（upsert で上書き）
            await todoist.upsert(BIG_SNOWFLAKE, "cipher-y", "proj", "今日やること", "admin")
            assert (await todoist.get(BIG_SNOWFLAKE))["api_token_encrypted"] == "cipher-y"
            # DELETE
            assert await todoist.delete(BIG_SNOWFLAKE) is True
            assert await todoist.get(BIG_SNOWFLAKE) is None

            # --- members / settings / layer_records（guild_id + TEXT の Snowflake 列）---
            members = MemberRepository(db)
            await members.upsert_team(BIG_SNOWFLAKE, "wing", "翼")
            await members.set_team_roles(BIG_SNOWFLAKE, "wing", member_role_id=big_role)
            assert (await members.get_team(BIG_SNOWFLAKE, "wing"))["member_role_id"] == big_role
            await members.upsert_member(BIG_SNOWFLAKE, big_user, "大きなIDの人", "wing")
            m = await members.get_member(BIG_SNOWFLAKE, big_user)
            assert m["display_name"] == "大きなIDの人"

            await db.set_setting(BIG_SNOWFLAKE, "DEFAULT_TASK_CHANNEL_ID", big_channel)
            assert await db.get_setting(BIG_SNOWFLAKE, "DEFAULT_TASK_CHANNEL_ID") == big_channel

            sessions = LayerSessionRepository(db)
            await sessions.add_record(
                BIG_SNOWFLAKE, big_user, "主桁", "1", "2026-01-01", "2026-01-01", 30
            )
            records = await sessions.list_records(BIG_SNOWFLAKE)
            assert [r["user_id"] for r in records] == [big_user]

            # 他ギルド（小さい ID）からは見えない
            assert await todoist.get(G1) is None
            assert await members.get_member(G1, big_user) is None
        finally:
            await db.execute("DELETE FROM todoist_configs WHERE guild_id = ?", (BIG_SNOWFLAKE,))
            await db.execute("DELETE FROM layer_records WHERE guild_id = ?", (BIG_SNOWFLAKE,))
            await db.execute("DELETE FROM members WHERE guild_id = ?", (BIG_SNOWFLAKE,))
            await db.execute("DELETE FROM teams WHERE guild_id = ?", (BIG_SNOWFLAKE,))
            await db.execute("DELETE FROM settings WHERE guild_id = ?", (BIG_SNOWFLAKE,))
            await db.close()

    run(_main())


def test_pg_live_bigint_migration_sql():
    """migrations/005_bigint_discord_ids.sql が既存 int4 スキーマを
    安全に BIGINT 化すること（ビュー依存を含む）を実 DB で検証する。

    手順: 旧不整合スキーマ（guild_id INTEGER）を手動再現 → 大きな ID で
    失敗することを確認 → 005 を適用 → 成功することを確認。
    """
    dsn = _guarded_dsn()

    async def _main():
        db = Database("./unused.db", database_url=dsn)
        await db.connect()
        mig_table = "mig_todoist_configs"
        try:
            # 旧不整合スキーマを再現（int4 + 依存ビュー付き）
            await db.execute(f"""
CREATE TABLE IF NOT EXISTS {mig_table} (
    guild_id            INTEGER PRIMARY KEY CHECK (guild_id > 0),
    api_token_encrypted TEXT NOT NULL,
    project_id          TEXT,
    today_label_name    TEXT NOT NULL DEFAULT '今日やること',
    enabled_flag        INTEGER NOT NULL DEFAULT 1,
    created_by          TEXT NOT NULL,
    created_at          TEXT NOT NULL,
    updated_at          TEXT NOT NULL
)""")
            await db.execute(
                f"CREATE OR REPLACE VIEW mig_v AS SELECT guild_id, project_id FROM {mig_table}"
            )

            # 小さい ID は入るが、2^31 超は int4 のため失敗するはず
            await db.execute(
                f"INSERT INTO {mig_table} (guild_id, api_token_encrypted,"
                f" created_by, created_at, updated_at) VALUES (1, 'c', 'a', 't', 't')"
            )
            failed = False
            try:
                await db.execute(
                    f"INSERT INTO {mig_table} (guild_id, api_token_encrypted,"
                    f" created_by, created_at, updated_at)"
                    f" VALUES (?, 'c', 'a', 't', 't')",
                    (BIG_SNOWFLAKE,),
                )
            # int4 範囲外で何らかの例外が出ること自体を検証するため例外種別は問わない
            except Exception:  # noqa: BLE001
                failed = True
            assert failed, "int4 では大きな ID が失敗するはず"

            # 005 と同等の手順（依存ビュー DROP → ALTER → ビュー再作成）
            await db.execute("DROP VIEW IF EXISTS mig_v")
            await db.execute(f"ALTER TABLE {mig_table} ALTER COLUMN guild_id TYPE BIGINT")
            await db.execute(
                f"CREATE OR REPLACE VIEW mig_v AS SELECT guild_id, project_id FROM {mig_table}"
            )
        finally:
            await db.close()

        # 注意: asyncpg はクエリ文字列単位でプリペアド文をキャッシュするため、
        # ALTER 前の int4 型推論が残る。本番でもマイグレーション適用後は
        # bot の再起動（接続プール再生成）が必要。ここでも接続を張り直す。
        db2 = Database("./unused.db", database_url=dsn)
        await db2.connect()
        try:
            # ALTER 後は 2^31 超でも INSERT/SELECT/DELETE できる
            await db2.execute(
                f"INSERT INTO {mig_table} (guild_id, api_token_encrypted,"
                f" created_by, created_at, updated_at)"
                f" VALUES (?, 'c', 'a', 't', 't')",
                (BIG_SNOWFLAKE,),
            )
            row = await db2.fetchone(
                f"SELECT guild_id FROM {mig_table} WHERE guild_id = ?", (BIG_SNOWFLAKE,)
            )
            assert row["guild_id"] == BIG_SNOWFLAKE
            rows = await db2.fetchall("SELECT guild_id FROM mig_v")
            assert BIG_SNOWFLAKE in {r["guild_id"] for r in rows}
            await db2.execute(f"DELETE FROM {mig_table} WHERE guild_id = ?", (BIG_SNOWFLAKE,))
        finally:
            await db2.execute("DROP VIEW IF EXISTS mig_v")
            await db2.execute(f"DROP TABLE IF EXISTS {mig_table}")
            await db2.close()

    run(_main())


# ---------------------------------------------------------------------
# ダッシュボードの行 ID（G1-0）
#
# ルータは URL の row_id を str で受け取り、_prepare() は型変換をしない。
# **SQLite は型親和性で '5' を 5 として扱うため、この不具合は
# PostgreSQL でしか再現しない**（G0-3 の実測で確定）。
#
#     asyncpg.exceptions.DataError: invalid input for query argument $2: '5'
#     ('str' object cannot be interpreted as an integer)
# ---------------------------------------------------------------------
def test_pg_live_dashboard_row_id_accepts_string():
    """str の row_id で bigint 主キーの表を読み書きできること。"""
    dsn = _guarded_dsn()

    async def _main():
        from repositories.member_repository import MemberRepository
        from repositories.table_repository import TableRepository, UnknownRowError

        db = Database("./unused.db", database_url=dsn)
        await db.connect()
        try:
            members = MemberRepository(db)
            repo = TableRepository(db)
            await members.upsert_member(G2, "9001", "行IDの型テスト")
            row = await db.fetchone(
                "SELECT member_id FROM members WHERE guild_id = ? AND user_id = ?", (G2, "9001")
            )
            member_id = int(row["member_id"])

            # URL 由来と同じ str を渡す（ここが DataError になっていた）
            row = await repo.get_row(G2, "members", str(member_id))
            assert row is not None and row["display_name"] == "行IDの型テスト"

            assert (
                await repo.update_row(G2, "members", str(member_id), {"display_name": "更新後"})
                is True
            )
            assert (await repo.get_row(G2, "members", str(member_id)))["display_name"] == "更新後"

            # 変換できない ID は DataError ではなく UnknownRowError（→ 404）
            try:
                await repo.get_row(G2, "members", "abc")
                raise AssertionError("UnknownRowError にならなかった")
            except UnknownRowError:
                pass

            # TEXT 主キーの表は str のまま扱える（int 化しない）
            assert await repo.get_row(G2, "schedules", "sch_missing") is None
        finally:
            await db.execute("DELETE FROM members WHERE guild_id = ?", (G2,))
            await db.close()

    run(_main())


def test_pg_live_layer_start_accepts_text_layer_num():
    """/layer start の層番号にテキスト（「シュリンク」等）を渡せること。

    回帰: layer_sessions.layer_num が INTEGER で作成されており、
    /layer start layer_num:test が
        DataError: invalid input for query argument $4: 'test'
        ('str' object cannot be interpreted as an integer)
    で失敗していた（スキーマ v16 で TEXT 化。SQLite は動的型付けのため
    再現しない）。
    """
    dsn = _guarded_dsn()

    async def _main():
        from repositories.layer_session_repository import LayerSessionRepository

        db = Database("./unused.db", database_url=dsn)
        await db.connect()
        try:
            # v16 適用後は text になっている
            col = await db.fetchone(
                "SELECT data_type FROM information_schema.columns"
                " WHERE table_name = 'layer_sessions' AND column_name = 'layer_num'"
            )
            assert col is not None and col["data_type"] == "text"

            repo = LayerSessionRepository(db)
            # ここが DataError になっていた（$4 = layer_num）
            await repo.start(G1, "u1", "主桁1", "シュリンク", "2026-08-26 10:00:00")
            row = await repo.get_by_user(G1, "u1")
            assert row is not None and row["layer_num"] == "シュリンク"

            # 数字入力も文字列のまま保持される
            await repo.start(G1, "u2", "主桁1", "3", "2026-08-26 10:00:00")
            assert (await repo.get_by_user(G1, "u2"))["layer_num"] == "3"

            # /layer end 相当（完了記録への引き渡し）も通る
            rid = await repo.add_record(
                G1,
                "u1",
                "主桁1",
                "シュリンク",
                "2026-08-26 10:00:00",
                "2026-08-26 11:00:00",
                60,
            )
            assert rid
            await repo.end(G1, "u1")
            assert await repo.get_by_user(G1, "u1") is None
        finally:
            await db.execute("DELETE FROM layer_sessions WHERE guild_id = ?", (G1,))
            await db.execute("DELETE FROM layer_records WHERE guild_id = ?", (G1,))
            await db.close()

    run(_main())


def test_pg_live_schedule_soft_delete_columns():
    """スキーマ v17 の2列が PostgreSQL にも存在し、論理削除が通ること。

    deleted_flag は G3-3（/schedule delete の論理削除）、
    confirmed_option_id は G3-4（確定日程）が使う。1つの版に2列を
    まとめてあるので、**両方**の存在をここで見る（v17 済みの DB は
    二度と v17 の処理を通らないため、後から足しても既存 DB には入らない）。
    """
    dsn = _guarded_dsn()

    async def _main():
        from repositories.schedule_repository import ScheduleRepository

        db = Database("./unused.db", database_url=dsn)
        await db.connect()
        try:
            cols = {
                r["column_name"]: r["data_type"]
                for r in await db.fetchall(
                    "SELECT column_name, data_type FROM information_schema.columns"
                    " WHERE table_name = 'schedules'"
                )
            }
            assert "deleted_flag" in cols, "v17 の deleted_flag が無い"
            assert "confirmed_option_id" in cols, "v17 の confirmed_option_id が無い"

            repo = ScheduleRepository(db)
            await db.execute("DELETE FROM schedules WHERE guild_id = ?", (G1,))
            await repo.create_schedule(
                G1, "pg_sch", "PG 用", None, None, None, "2026-10-01T23:59:00", "u1", "1"
            )
            await repo.add_option(G1, "pg_opt", "pg_sch", "10/1", "2026-10-01T18:00:00", None, None)
            await repo.set_vote(G1, "pg_opt", "u9", "ok")

            await repo.soft_delete_schedule(G1, "pg_sch")
            assert await repo.get_schedule(G1, "pg_sch") is None
            row = await repo.get_schedule(G1, "pg_sch", include_deleted=True)
            assert row is not None and row["deleted_flag"] == 1
            assert len(await repo.list_schedule_votes(G1, "pg_sch")) == 1, "票が消えている"

            assert await repo.restore_schedule(G1, "pg_sch") is True
            assert await repo.get_schedule(G1, "pg_sch") is not None
        finally:
            await db.execute("DELETE FROM schedules WHERE guild_id = ?", (G1,))
            await db.close()

    run(_main())


def test_pg_live_confirmed_schedule_join():
    """確定日程の JOIN が PostgreSQL でも動くこと（G3-4）。

    start_at は TEXT に `+09:00` 付きの ISO 文字列で入る。範囲比較の境界を
    naive な文字列で作ると、ちょうど 00:00:00 の行を取りこぼす。
    """
    dsn = _guarded_dsn()

    async def _main():
        from datetime import datetime, timedelta

        from repositories.schedule_repository import ScheduleRepository
        from utils.parser import TZ, to_iso

        db = Database("./unused.db", database_url=dsn)
        await db.connect()
        try:
            await db.execute("DELETE FROM schedules WHERE guild_id = ?", (G1,))
            repo = ScheduleRepository(db)
            start = datetime(2026, 10, 1, 0, 0, tzinfo=TZ)
            await repo.create_schedule(
                G1, "pg_conf", "PG 確定", None, "部室", None, to_iso(start), "u1", "1"
            )
            # ちょうど 00:00:00 の候補（境界）
            await repo.add_option(G1, "pg_conf_o1", "pg_conf", "10/1", to_iso(start), None, None)
            assert await repo.set_confirmed_option(G1, "pg_conf", "pg_conf_o1") is True
            # 存在しない候補は書けない
            assert await repo.set_confirmed_option(G1, "pg_conf", "no_such_option") is False
            # **他の予定に属する実在の候補**も書けない（現実的な誤操作はこちら）
            await repo.create_schedule(
                G1, "pg_conf2", "PG 確定2", None, None, None, to_iso(start), "u1", "1"
            )
            await repo.add_option(G1, "pg_conf2_o1", "pg_conf2", "10/1", to_iso(start), None, None)
            assert await repo.set_confirmed_option(G1, "pg_conf", "pg_conf2_o1") is False

            rows = await repo.list_confirmed_between(
                G1, to_iso(start), to_iso(start + timedelta(days=1))
            )
            assert len(rows) == 1, "境界（00:00:00）の候補を取りこぼしている"
            assert rows[0]["confirmed_start_at"] == to_iso(start)

            # 予定は2件あるので1件決め打ちで unpack しない
            listed = {r["schedule_id"]: r for r in await repo.list_open_schedules(G1)}
            assert listed["pg_conf"]["confirmed_start_at"] == to_iso(start)
            assert listed["pg_conf2"]["confirmed_start_at"] is None, "確定していない予定に日時が付いている"
        finally:
            await db.execute("DELETE FROM schedules WHERE guild_id = ?", (G1,))
            await db.close()

    run(_main())


if __name__ == "__main__":
    test_to_pg_ddl_autoincrement_and_guild_id()
    print("test_to_pg_ddl_autoincrement_and_guild_id: OK")
    test_to_pg_ddl_preserves_constraints()
    print("test_to_pg_ddl_preserves_constraints: OK")
    test_view_ddl_separation()
    print("test_view_ddl_separation: OK")
    test_sqlite_view_init_idempotent()
    print("test_sqlite_view_init_idempotent: OK")
    test_pg_ddl_no_unsupported_constructs()
    print("test_pg_ddl_no_unsupported_constructs: OK")
    test_prepare_converts_placeholders()
    print("test_prepare_converts_placeholders: OK")
    test_prepare_sqlite_passthrough()
    print("test_prepare_sqlite_passthrough: OK")
    test_driver_name()
    print("test_driver_name: OK")
    if os.getenv("CLUB_TEST_PG_DSN"):
        test_pg_live_schema_and_crud()
        print("test_pg_live_schema_and_crud: OK")
        test_pg_live_sequence_fix()
        print("test_pg_live_sequence_fix: OK")
        test_pg_live_big_snowflake_crud()
        print("test_pg_live_big_snowflake_crud: OK")
        test_pg_live_bigint_migration_sql()
        print("test_pg_live_bigint_migration_sql: OK")
        test_pg_live_dashboard_row_id_accepts_string()
        print("test_pg_live_dashboard_row_id_accepts_string: OK")
        test_pg_live_layer_start_accepts_text_layer_num()
        print("test_pg_live_layer_start_accepts_text_layer_num: OK")
        test_pg_live_schedule_soft_delete_columns()
        print("test_pg_live_schedule_soft_delete_columns: OK")
        test_pg_live_confirmed_schedule_join()
        print("test_pg_live_confirmed_schedule_join: OK")
    else:
        print("ライブ PG テストは CLUB_TEST_PG_DSN 未設定のためスキップ")
    print("全テスト成功")
