-- =====================================================================
-- 007_members_member_id.sql
--
-- members に代理主キー member_id を追加する（スキーマバージョン 8）。
-- 旧主キー (guild_id, user_id) は UNIQUE 制約として維持する。
--
-- 背景:
--   Directus は各コレクションに「単一列の主キー」を要求するため、
--   複合主キー (guild_id, user_id) のままでは members を Directus から
--   扱えない。自然キーの一意性は UNIQUE 制約で維持されるため、
--   リポジトリ層のクエリ（guild_id + user_id 指定）は変更不要。
--
-- 使い方（sqlite3 CLI）:
--   1. 必ず DB のバックアップを取る:
--        cp data/club.db data/club.db.bak
--   2. 実行:
--        sqlite3 data/club.db ".read migrations/007_members_member_id.sql"
--   ※ SQLite は主キーの変更を ALTER でできないためテーブル再作成方式。
--     member_id は自動採番されるためコピー対象の列から除外している。
--   ※ 既に member_id がある DB では 1 文目の ALTER が
--     「no such table: members」等で失敗する。その場合は適用不要。
--
-- 使い方（PostgreSQL）:
--   1. 事前バックアップ:
--        docker compose -f deploy/docker-compose.directus.yml exec postgres \
--          pg_dump -U clubbot clubdb > backup_$(date +%Y%m%d).sql
--   2. 適用（下部の PostgreSQL 版を参照）
--
-- ※ Bot 側の自動マイグレーション（_migrate_v8_members_surrogate_pk）が
--   同等の処理を行うため、通常は Bot を起動するだけでよい。
-- ※ 本スクリプトは user_version を更新しない。Bot 起動時に 8 に更新される。
-- =====================================================================

BEGIN TRANSACTION;

ALTER TABLE members RENAME TO members_legacy;

CREATE TABLE members (
    member_id       INTEGER PRIMARY KEY AUTOINCREMENT,
    guild_id        INTEGER NOT NULL CHECK (guild_id >= 0),
    user_id         TEXT NOT NULL,
    display_name    TEXT NOT NULL,
    primary_team    TEXT,
    secondary_teams TEXT,
    is_leader       INTEGER NOT NULL DEFAULT 0,
    skills          TEXT,
    notes           TEXT,
    joined_at       TEXT NOT NULL,
    active_flag     INTEGER NOT NULL DEFAULT 1,
    UNIQUE (guild_id, user_id)
);

INSERT INTO members (guild_id, user_id, display_name, primary_team,
                     secondary_teams, is_leader, skills, notes,
                     joined_at, active_flag)
SELECT guild_id, user_id, display_name, primary_team,
       secondary_teams, is_leader, skills, notes,
       joined_at, active_flag
FROM members_legacy;

DROP TABLE members_legacy;

CREATE INDEX IF NOT EXISTS idx_members_guild ON members(guild_id, active_flag);

COMMIT;

-- 検証クエリ例（移行前後で件数が一致すること）:
--   PRAGMA table_info(members);
--   SELECT COUNT(*) FROM members;

-- ---------------------------------------------------------------------
-- PostgreSQL 版（psql で実行する。上の SQLite 版は実行しないこと）
-- ---------------------------------------------------------------------
-- BEGIN;
-- CREATE UNIQUE INDEX IF NOT EXISTS members_guild_user_uniq
--     ON members (guild_id, user_id);
-- ALTER TABLE members DROP CONSTRAINT IF EXISTS members_pkey;
-- ALTER TABLE members ADD COLUMN member_id BIGINT
--     GENERATED BY DEFAULT AS IDENTITY;
-- ALTER TABLE members ADD PRIMARY KEY (member_id);
-- COMMIT;
--
-- 検証:
--   SELECT column_name, data_type FROM information_schema.columns
--   WHERE table_name = 'members' ORDER BY ordinal_position;
