-- =====================================================================
-- 009_progress_nodes.sql
--
-- 機体進捗ツリーを DB で保持するテーブル群を追加する
-- （スキーマバージョン 10）。
--
-- 背景:
--   /progress だけが進捗データの正本を中央 Google スプレッドシートに
--   置いており、導入サークルは自分のシートをホスト側のサービスアカウントに
--   共有する手作業を強いられていた（公開配布の要件「.env を編集しなくてよい」
--   を崩している唯一の箇所）。正本を他機能と同じ DB へ移し、
--   GOOGLE_CREDENTIALS_PATH なしで /progress が完全動作するようにする。
--   詳細は club-bot/docs/DESIGN_PUBLIC_DISTRIBUTION.md 1.3 / Phase 1。
--
-- 追加するテーブル:
--   progress_nodes         : 機体 → パーツ → 部品 → … の隣接リスト（深さ無制限）
--   progress_todoist_links : Todoist プロジェクト → ノードの紐付け
--                            （旧「Todoist対応表」シート）
--   progress_spar_links    : 桁 → ノードの紐付けと目標層数
--                            （旧「桁巻き対応表」シート ＋「桁マスタ」）
--
-- 重要な設計上の変更:
--   旧構成では中央シート1枚を複数の Discord サーバーで共有できたが、
--   本テーブルは guild_id スコープであり、**進捗ツリーはサーバーごとに
--   独立**する。複数サーバーで同じ機体を管理していた場合は、
--   scripts/migrate_progress_sheet_to_db.py を各サーバーに対して実行する
--   （同じシートを複数ギルドへ取り込める）。
--
-- 後方互換:
--   既存テーブルには一切触れない。進捗データが無いギルドは空のツリーとして
--   扱われ、/progress view は「進捗データがありません」を返す。
--
-- 適用方法:
--   通常は bot 起動時に utils/db.py の _migrate_v10_progress_tables() が
--   自動適用する（SQLite / PostgreSQL 共通）。本ファイルは PostgreSQL で
--   手動適用する場合・レビュー用の参照定義。
--
--   psql "$DATABASE_URL" -f migrations/009_progress_nodes.sql
--
-- 冪等性:
--   CREATE TABLE / CREATE INDEX いずれも IF NOT EXISTS のため、
--   繰り返し実行しても安全。
-- =====================================================================

BEGIN;

-- ---------------------------------------------------------------------
-- 進捗ツリー本体
--
-- node_id   : ギルド内で一意な業務キー。人手入力の任意文字列のほか、
--             `pj_<Todoistプロジェクト ID>` / `td_<Todoistタスク ID>` を使う
-- parent_id : 同一ギルドの node_id。ルート（機体）は NULL
--             外部キーは張らない（移行・同期で親より先に子が入る順序を
--             許すため。孤児・循環は services/progress_tree.py が検出して
--             ツリーから除外し #bot-log へ通知する）
-- manual_progress : 0.0〜1.0。NULL は未入力（葉なら 0 として集計）
-- source    : manual / todoist / spar_winding。manual 行は同期処理が
--             上書きしない
-- weight    : 集計時の重み。現状すべて 1（将来の重み付け平均用）
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS progress_nodes (
    progress_node_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    guild_id        BIGINT NOT NULL CHECK (guild_id >= 0),
    node_id         TEXT NOT NULL,
    parent_id       TEXT,
    sort_order      DOUBLE PRECISION NOT NULL DEFAULT 0,
    name            TEXT NOT NULL DEFAULT '',
    assignee        TEXT,
    status          TEXT,
    manual_progress DOUBLE PRECISION,
    source          TEXT NOT NULL DEFAULT 'manual',
    todoist_task_id TEXT,
    weight          DOUBLE PRECISION NOT NULL DEFAULT 1,
    created_at      TEXT NOT NULL,
    updated_at      TEXT NOT NULL,
    UNIQUE (guild_id, node_id)
);

-- ---------------------------------------------------------------------
-- Todoist プロジェクト → ノードの紐付け（旧「Todoist対応表」シート）
--
-- notify_channel_id が空のときは settings の PROGRESS_DEFAULT_CHANNEL_ID、
-- それも無ければギルド既定のタスクチャンネルへフォールバックする。
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS progress_todoist_links (
    link_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    guild_id          BIGINT NOT NULL CHECK (guild_id >= 0),
    project_name      TEXT NOT NULL,
    node_id           TEXT NOT NULL,
    notify_channel_id TEXT,
    created_by        TEXT,
    created_at        TEXT NOT NULL,
    updated_at        TEXT NOT NULL,
    UNIQUE (guild_id, project_name)
);

-- ---------------------------------------------------------------------
-- 桁 → ノードの紐付けと目標層数
-- （旧「桁巻き対応表」シート ＋ 桁巻きブックの「桁マスタ」）
--
-- 完了層数は layer_records（/layer end の記録）から数えるため、
-- 別ブックの桁巻きスプレッドシートは不要になる。
-- keta_name は layer_keta.keta_name と同じ値を指す（桁名の無効化と
-- 進捗の紐付けを独立に扱うため外部キーは張らない）。
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS progress_spar_links (
    spar_link_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    guild_id      BIGINT NOT NULL CHECK (guild_id >= 0),
    keta_name     TEXT NOT NULL,
    node_id       TEXT NOT NULL,
    target_layers INTEGER NOT NULL CHECK (target_layers > 0),
    created_at    TEXT NOT NULL,
    updated_at    TEXT NOT NULL,
    UNIQUE (guild_id, keta_name)
);

-- ---------------------------------------------------------------------
-- インデックス（guild_id を先頭に含む）
-- ---------------------------------------------------------------------
CREATE INDEX IF NOT EXISTS idx_progress_nodes_guild_parent
    ON progress_nodes(guild_id, parent_id);
CREATE INDEX IF NOT EXISTS idx_progress_nodes_guild_source
    ON progress_nodes(guild_id, source);
CREATE INDEX IF NOT EXISTS idx_progress_todoist_links_guild
    ON progress_todoist_links(guild_id);
CREATE INDEX IF NOT EXISTS idx_progress_spar_links_guild
    ON progress_spar_links(guild_id);

-- スキーマバージョンを 10 へ
INSERT INTO schema_meta (id, version) VALUES (1, 10)
    ON CONFLICT (id) DO UPDATE SET version = EXCLUDED.version;

COMMIT;

-- =====================================================================
-- 適用後の確認
-- =====================================================================
-- SELECT table_name FROM information_schema.tables
--  WHERE table_name LIKE 'progress\_%';
-- SELECT version FROM schema_meta WHERE id = 1;   -- 10 になっていること
