-- =====================================================================
-- 012_progress_milestones.sql
--
-- 大会日からの逆算アラート用のマイルストーンを追加する
-- （スキーマバージョン 13）。
--
-- 背景:
--   /progress で進捗率は見えるが「大会に間に合うのか」が見えない。
--   ノードごとに期限（マイルストーン）を置き、大会日から逆算した
--   必要ペースと実績ペースを比べて、遅延を先に知らせる。
--
-- 設計:
--   大会日そのものはこのテーブルに持たず、ギルド別設定 COMPETITION_DATE
--   （YYYY-MM-DD）に置く。**既定値は持たない** — 大会も日程もサークルごとに
--   違うため、未設定なら /countdown は設定方法を案内して終わる。
--
--   node_id には外部キーを張らない。progress_nodes と同じ方針で、
--   同期・移行の途中に親より先に子が入る順序を許すため。存在しない
--   ノードを指すマイルストーンは表示から除外する。
--
--   UNIQUE (guild_id, node_id, name) により、同じノードに同名の
--   マイルストーンは1つだけ。同じ名前で登録し直すと期限が更新される。
--
-- 後方互換:
--   新規テーブルの追加のみ。既存テーブルには一切触れない。
--   マイルストーンを登録していないサーバーの挙動は変わらない。
--
-- 適用方法:
--   通常は bot 起動時に utils/db.py の _migrate_v13_progress_milestones() が
--   自動適用する（SQLite / PostgreSQL 共通）。本ファイルは PostgreSQL で
--   手動適用する場合・レビュー用の参照定義。
--
--   psql "$DATABASE_URL" -f migrations/012_progress_milestones.sql
--
-- 冪等性:
--   CREATE TABLE / CREATE INDEX いずれも IF NOT EXISTS のため、
--   繰り返し実行しても安全。
-- =====================================================================

BEGIN;

CREATE TABLE IF NOT EXISTS progress_milestones (
    milestone_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    guild_id     BIGINT NOT NULL CHECK (guild_id >= 0),
    node_id      TEXT NOT NULL,
    name         TEXT NOT NULL,
    due_date     TEXT NOT NULL,
    created_at   TEXT NOT NULL,
    updated_at   TEXT NOT NULL,
    UNIQUE (guild_id, node_id, name)
);

-- 期限順の取り出しに使う
CREATE INDEX IF NOT EXISTS idx_progress_milestones_guild_due
    ON progress_milestones(guild_id, due_date);

-- スキーマバージョンを 13 へ
INSERT INTO schema_meta (id, version) VALUES (1, 13)
    ON CONFLICT (id) DO UPDATE SET version = EXCLUDED.version;

COMMIT;

-- =====================================================================
-- 適用後の確認
-- =====================================================================
-- SELECT column_name FROM information_schema.columns
--  WHERE table_name = 'progress_milestones';
-- SELECT version FROM schema_meta WHERE id = 1;   -- 13 になっていること
