-- =====================================================================
-- 013_seasons.sql
--
-- 年度（世代）の境界とメンバーの在籍状態を追加する
-- （スキーマバージョン 14）。
--
-- 背景:
--   サークルには毎年必ず代替わりが来るのに、区切りを表す仕組みが
--   まったく無かった。docs/GUIDE.md には「年度替わりの引き継ぎ」の章が
--   あるのに、コマンドとしては何も用意されていない状態だった。
--
-- 設計（重要）:
--   **全テーブルに season_id は張らない。** 既存の全テーブルへの列追加と
--   全クエリの改修は後方互換に対するリスクが大きすぎる。各記録には
--   created_at があるので、年度での絞り込みは日付範囲で足りる。
--   ここで持つのは「年度の境界（seasons）」と「在籍状態（members.status）」
--   の2つだけ。
--
--   年度名に既定値は持たない（「2026年度」も「第30代」もサークル次第）。
--   「現役の年度」は ended_at IS NULL のうち最新1件。
--
-- 後方互換（ここが最も重要）:
--   status は NOT NULL DEFAULT 'active' で追加するため、
--   **既存メンバーは全員そのまま active になる**。マイグレーションによって
--   誰かが勝手に卒業扱いになることはない。在籍状態が変わるのは
--   /season rollover を明示的に実行したときだけ。
--   left_season は NULL 許容。
--
--   卒業者の行は削除しない。過去の作業記録に残る担当者名が引けなくなるため。
--
-- 適用方法:
--   通常は bot 起動時に utils/db.py の _migrate_v14_seasons() が
--   自動適用する（SQLite / PostgreSQL 共通）。本ファイルは PostgreSQL で
--   手動適用する場合・レビュー用の参照定義。
--
--   psql "$DATABASE_URL" -f migrations/013_seasons.sql
--
-- 冪等性:
--   CREATE TABLE / ADD COLUMN / CREATE INDEX いずれも IF NOT EXISTS のため、
--   繰り返し実行しても安全。
-- =====================================================================

BEGIN;

-- 年度（世代）の境界
CREATE TABLE IF NOT EXISTS seasons (
    season_id  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    guild_id   BIGINT NOT NULL CHECK (guild_id >= 0),
    name       TEXT NOT NULL,
    started_at TEXT NOT NULL,
    ended_at   TEXT,
    created_at TEXT NOT NULL,
    UNIQUE (guild_id, name)
);

-- 在籍状態: active（現役） / alumni（卒業） / inactive（休止）
-- 既存メンバーは DEFAULT により全員 active になる
ALTER TABLE members
    ADD COLUMN IF NOT EXISTS status TEXT NOT NULL DEFAULT 'active';

-- 卒業した年度の名前（seasons.name）。在籍中は NULL
ALTER TABLE members
    ADD COLUMN IF NOT EXISTS left_season TEXT;

CREATE INDEX IF NOT EXISTS idx_seasons_guild_ended
    ON seasons(guild_id, ended_at);
CREATE INDEX IF NOT EXISTS idx_members_guild_status
    ON members(guild_id, status);

-- スキーマバージョンを 14 へ
INSERT INTO schema_meta (id, version) VALUES (1, 14)
    ON CONFLICT (id) DO UPDATE SET version = EXCLUDED.version;

COMMIT;

-- =====================================================================
-- 適用後の確認
-- =====================================================================
-- SELECT status, COUNT(*) FROM members GROUP BY status;
--   -- 移行直後は全員 active になっていること
-- SELECT version FROM schema_meta WHERE id = 1;   -- 14 になっていること
