-- =====================================================================
-- 017_progress_snapshots.sql
--
-- 進捗の日次スナップショットを追加する（スキーマバージョン 18）。
--
-- 背景:
--   progress_nodes は「現在値」しか持たないため、実績ペースが
--   「作成日 → 最終更新日の平均」でしか出せなかった（ADR 0022）。
--   これは**停滞期間を含まない**近似で、判定不能も多く出る。
--   「先週から何%進んだか」も分からなかった。
--
--   ADR 0022 の「覆す条件」は
--   「進捗の履歴が必要な別機能が出てきたとき。その時点で A（履歴テーブル）へ移行する」。
--   /progress history と週次ダイジェスト（G4-5）がまさにそれにあたる。
--
-- 設計:
--   - snapshot_date は 'YYYY-MM-DD'。UNIQUE (guild_id, node_id, snapshot_date) が
--     「1日1行」を**構造で**保証する（アプリ側の if に頼らない。ADR 0008 / 0016）
--   - aggregated / actual_weight_g は **NULL 許容**。未集計・未計測を 0.0 に
--     丸めない（ADR 0021）
--   - node_id に外部キーを張らない（progress_nodes と同じ既存方針。ADR 0019）。
--     ノードが消えても過去の履歴は残る
--   - 書き込みは20分ごとの定期同期の末尾。その日まだ書いていなければ1回だけ
--
-- 後方互換:
--   **追加されるのは空のテーブルだけで、既存データには一切触れない。**
--   履歴は次の定期同期から積まれる。溜まるまではペース算出が従来の推定
--   （作成日→更新日）にフォールバックするので、マイグレーション直後に
--   マイルストーンの判定結果が変わることはない（ADR 0024）。
--
-- 適用方法:
--   通常は bot 起動時に utils/db.py の _migrate_v18_progress_snapshots() が
--   自動適用する（SQLite / PostgreSQL 共通）。本ファイルは PostgreSQL で
--   手動適用する場合・レビュー用の参照定義。
--
--   psql "$DATABASE_URL" -f migrations/017_progress_snapshots.sql
--
-- 注意:
--   - down はない（このリポジトリのマイグレーションは全て up のみ）。
--     適用前に pg_dump -Fc を取ること（docs/OPERATION.md §6 / docs/DASHBOARD_SETUP.md §11）
--   - asyncpg はクエリ文字列単位でプリペアド文をキャッシュするため、
--     手動適用後は bot を再起動して接続プールを作り直すこと（migrations/005 と同じ注意点）
--
-- 冪等性:
--   CREATE TABLE IF NOT EXISTS / CREATE INDEX IF NOT EXISTS のため
--   繰り返し実行しても安全。
-- =====================================================================

BEGIN;

CREATE TABLE IF NOT EXISTS progress_snapshots (
    snapshot_id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    guild_id        BIGINT NOT NULL CHECK (guild_id >= 0),
    node_id         TEXT NOT NULL,
    snapshot_date   TEXT NOT NULL,
    aggregated      DOUBLE PRECISION,
    actual_weight_g DOUBLE PRECISION,
    UNIQUE (guild_id, node_id, snapshot_date)
);

CREATE INDEX IF NOT EXISTS idx_progress_snapshots_node
    ON progress_snapshots(guild_id, node_id, snapshot_date);

-- スキーマバージョンを 18 へ
INSERT INTO schema_meta (id, version) VALUES (1, 18)
    ON CONFLICT (id) DO UPDATE SET version = EXCLUDED.version;

COMMIT;

-- =====================================================================
-- 適用後の確認
-- =====================================================================
-- SELECT column_name, data_type, is_nullable FROM information_schema.columns
--  WHERE table_name = 'progress_snapshots' ORDER BY ordinal_position;
--  -- aggregated / actual_weight_g が double precision かつ NULL 許容であること
-- SELECT COUNT(*) FROM progress_snapshots;   -- 0 であること（既存データは動かない）
-- SELECT version FROM schema_meta WHERE id = 1;  -- 18 になっていること
