-- =====================================================================
-- 018_stock.sql
--
-- 資材・消耗品の在庫と発注アラート（スキーマバージョン 19）。
--
-- 背景:
--   人力飛行機で最も痛いのは「プリプレグが無くて桁が巻けない」。
--   カーボンプリプレグは納期が数週間で、切れてから気づくと工程が1ヶ月ずれる。
--   発注判断は「残量が閾値を割った」という、bot が自動で見張れる条件。
--
-- 設計:
--   - **品目名の初期値はコードにも DDL にも持たない**（何を在庫管理するかは
--     サークルごとに違う。AGENTS.md「組織構造は可変」）。
--     マスタ管理は layer_keta と同型（active_flag ＋ (guild_id, item_name) で一意）
--   - threshold は **NULL 許容**。閾値を決めていない品目を 0 扱いにしない
--     （0 にすると「在庫0でも閾値割れではない」という嘘になる。ADR 0021）
--   - quantity / threshold は REAL / double precision。
--     「2.5 m」「0.5 L」のような単位を扱う
--   - low_notified_flag は「閾値割れの即時通知を送ったか」。閾値以上へ戻ると
--     0 に戻るので、割り込むたびに1回だけ通知が飛ぶ
--   - stock_movements.stock_item_id に外部キーを張らない
--     （progress_nodes と同じ既存方針。ADR 0019。品目を消しても履歴は残る）
--
-- 後方互換:
--   **追加されるのは空のテーブル2つだけで、既存データには一切触れない。**
--   品目が0件のギルドでは /stock list が空状態を出し、朝の通知も飛ばない（ADR 0024）。
--
-- 適用方法:
--   通常は bot 起動時に utils/db.py の _migrate_v19_stock() が自動適用する
--   （SQLite / PostgreSQL 共通）。本ファイルは PostgreSQL で手動適用する場合・
--   レビュー用の参照定義。
--
--   psql "$DATABASE_URL" -f migrations/018_stock.sql
--
-- 注意:
--   - down はない（このリポジトリのマイグレーションは全て up のみ）。
--     適用前に pg_dump -Fc を取ること（docs/OPERATION.md §6 / docs/DASHBOARD_SETUP.md §11）
--   - asyncpg はクエリ文字列単位でプリペアド文をキャッシュするため、
--     手動適用後は bot を再起動して接続プールを作り直すこと（migrations/005 と同じ注意点）
--
-- 冪等性:
--   CREATE TABLE / CREATE INDEX IF NOT EXISTS のため繰り返し実行しても安全。
-- =====================================================================

BEGIN;

CREATE TABLE IF NOT EXISTS stock_items (
    stock_item_id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    guild_id          BIGINT NOT NULL CHECK (guild_id >= 0),
    item_name         TEXT NOT NULL,
    unit              TEXT NOT NULL DEFAULT '個',
    quantity          DOUBLE PRECISION NOT NULL DEFAULT 0,
    threshold         DOUBLE PRECISION,
    note              TEXT,
    active_flag       INTEGER NOT NULL DEFAULT 1,
    low_notified_flag INTEGER NOT NULL DEFAULT 0,
    created_by        TEXT NOT NULL,
    created_at        TEXT NOT NULL,
    updated_at        TEXT NOT NULL,
    UNIQUE (guild_id, item_name)
);

CREATE TABLE IF NOT EXISTS stock_movements (
    movement_id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    guild_id      BIGINT NOT NULL CHECK (guild_id >= 0),
    stock_item_id BIGINT NOT NULL,
    delta         DOUBLE PRECISION NOT NULL,
    reason        TEXT,
    user_id       TEXT NOT NULL,
    created_at    TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_stock_items_guild ON stock_items(guild_id, active_flag);
CREATE INDEX IF NOT EXISTS idx_stock_movements_item
    ON stock_movements(guild_id, stock_item_id, created_at);

-- スキーマバージョンを 19 へ
INSERT INTO schema_meta (id, version) VALUES (1, 19)
    ON CONFLICT (id) DO UPDATE SET version = EXCLUDED.version;

COMMIT;

-- =====================================================================
-- 適用後の確認
-- =====================================================================
-- SELECT column_name, data_type, is_nullable FROM information_schema.columns
--  WHERE table_name = 'stock_items' ORDER BY ordinal_position;
--  -- threshold が double precision かつ NULL 許容であること
-- SELECT COUNT(*) FROM stock_items;   -- 0 であること（初期品目を入れない）
-- SELECT version FROM schema_meta WHERE id = 1;  -- 19 になっていること
