-- =====================================================================
-- 019_tools.sql
--
-- 工具・機材の貸出管理（スキーマバージョン 20）。
--
-- 背景:
--   `/layer start` → `/layer end` とまったく同じ「開始 → 進行中 → 終了」モデル。
--   借りたまま返らない工具は、次に使う人の作業日をそのまま潰す。
--
-- **v19（在庫）に足さないこと。**
--   utils/db.py の _migrate_versioned() は version >= SCHEMA_VERSION で
--   早期 return するため、v19 済みの DB は二度と v19 の処理を通らない。
--   後から v19 へ CREATE を足すと**新規 DB にだけテーブルがある**状態になり、
--   本番だけ「relation does not exist」で落ちる
--   （ClaudeVault gotcha `bot-wont-start-undefined-column` と同型）。
--   改善タスク表の v19 の欄は当初「在庫・工具」と書かれていたが、
--   この理由で工具は v20 に分けた。
--
-- 設計:
--   - 貸出中かどうかは **tool_loans に returned_at が NULL の行があるか**で表す。
--     tools 側にフラグを置くと、行を消したときに貸出の事実まで消える
--   - due_date は **NULL 許容**。返却予定日を決めていない貸出を「本日返却」に
--     しない（ADR 0021）。督促は due_date がある貸出だけを対象にする
--   - tools は layer_keta と同型（active_flag ＋ (guild_id, tool_name) で一意）
--   - tool_loans.tool_id に外部キーを張らない（ADR 0019）。工具を消しても履歴は残る
--   - **工具名の初期値は持たない**（何を貸出管理するかはサークルごとに違う）
--
-- 後方互換:
--   追加されるのは空のテーブル2つだけで、既存データには一切触れない（ADR 0024）。
--
-- 適用方法:
--   通常は bot 起動時に utils/db.py の _migrate_v20_tools() が自動適用する。
--   本ファイルは PostgreSQL で手動適用する場合・レビュー用の参照定義。
--
--   psql "$DATABASE_URL" -f migrations/019_tools.sql
--
-- 注意:
--   - down はない。適用前に pg_dump -Fc を取ること
--   - asyncpg のプリペアド文キャッシュのため、手動適用後は bot を再起動すること
--
-- 冪等性:
--   CREATE TABLE / CREATE INDEX IF NOT EXISTS のため繰り返し実行しても安全。
-- =====================================================================

BEGIN;

CREATE TABLE IF NOT EXISTS tools (
    tool_id     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    guild_id    BIGINT NOT NULL CHECK (guild_id >= 0),
    tool_name   TEXT NOT NULL,
    note        TEXT,
    active_flag INTEGER NOT NULL DEFAULT 1,
    created_by  TEXT NOT NULL,
    created_at  TEXT NOT NULL,
    UNIQUE (guild_id, tool_name)
);

CREATE TABLE IF NOT EXISTS tool_loans (
    loan_id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    guild_id              BIGINT NOT NULL CHECK (guild_id >= 0),
    tool_id               BIGINT NOT NULL,
    user_id               TEXT NOT NULL,
    borrowed_at           TEXT NOT NULL,
    due_date              TEXT,
    returned_at           TEXT,
    note                  TEXT,
    overdue_notified_flag INTEGER NOT NULL DEFAULT 0
);

CREATE INDEX IF NOT EXISTS idx_tools_guild ON tools(guild_id, active_flag);
CREATE INDEX IF NOT EXISTS idx_tool_loans_open ON tool_loans(guild_id, returned_at, tool_id);

-- スキーマバージョンを 20 へ
INSERT INTO schema_meta (id, version) VALUES (1, 20)
    ON CONFLICT (id) DO UPDATE SET version = EXCLUDED.version;

COMMIT;

-- =====================================================================
-- 適用後の確認
-- =====================================================================
-- SELECT column_name, data_type, is_nullable FROM information_schema.columns
--  WHERE table_name = 'tool_loans' ORDER BY ordinal_position;
--  -- due_date / returned_at が NULL 許容であること
-- SELECT COUNT(*) FROM tools;   -- 0 であること（初期の工具を入れない）
-- SELECT version FROM schema_meta WHERE id = 1;  -- 20 になっていること
