-- =====================================================================
-- 020_incidents.sql
--
-- ヒヤリハット・事故報告（スキーマバージョン 21）。
--
-- **当初 v20 / 019_incidents.sql を予約していたが、G4-9（工具の貸出）が
--   v20 を使ったので1つずらした**（docs/IMPROVEMENT_TASKS.md の割り当て表も更新済み）。
--
-- 背景:
--   工房での切削・溶剤・高所作業・機体運搬・テストフライトと危険度が高く、
--   大学から安全管理体制の提示を求められることもある。
--   今は「危なかった」が雑談チャンネルに流れて消えている。
--
-- 匿名の扱い（この設計の要点）:
--   - reporter_id は**匿名報告でも必ず保存する**。悪用・虚偽報告への対処に要る
--   - ただし reporter_id は**表示にもエクスポートにも出さない**。
--     repositories/table_repository.py の列ホワイトリストから外してあるので、
--     ダッシュボードにも /data export にも構造的に現れない（ADR 0016）
--   - reporter_name は「表示してよい名前」。匿名報告では NULL。
--     表示側はこちらしか見ないため、匿名の約束が if ではなくデータ形状で守られる
--   - この扱いは docs/PRIVACY.md に明記すること（隠された保持をしない）
--
-- injury（けがの有無）は自由記述。「軽い擦り傷」「無し」など、
-- 選択肢に収まらない実態を書けるようにする。
--
-- 後方互換:
--   追加されるのは空のテーブル1つだけで、既存データには一切触れない（ADR 0024）。
--
-- 適用方法:
--   通常は bot 起動時に utils/db.py の _migrate_v21_incidents() が自動適用する。
--   本ファイルは PostgreSQL で手動適用する場合・レビュー用の参照定義。
--
--   psql "$DATABASE_URL" -f migrations/020_incidents.sql
--
-- 注意:
--   - down はない。適用前に pg_dump -Fc を取ること
--   - asyncpg のプリペアド文キャッシュのため、手動適用後は bot を再起動すること
--
-- 冪等性:
--   CREATE TABLE / CREATE INDEX IF NOT EXISTS のため繰り返し実行しても安全。
-- =====================================================================

BEGIN;

CREATE TABLE IF NOT EXISTS incidents (
    incident_id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    guild_id       BIGINT NOT NULL CHECK (guild_id >= 0),
    occurred_at    TEXT NOT NULL,
    place          TEXT NOT NULL,
    description    TEXT NOT NULL,
    injury         TEXT,
    prevention     TEXT,
    anonymous_flag INTEGER NOT NULL DEFAULT 0,
    reporter_id    TEXT NOT NULL,
    reporter_name  TEXT,
    created_at     TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_incidents_guild ON incidents(guild_id, occurred_at);

-- スキーマバージョンを 21 へ
INSERT INTO schema_meta (id, version) VALUES (1, 21)
    ON CONFLICT (id) DO UPDATE SET version = EXCLUDED.version;

COMMIT;

-- =====================================================================
-- 適用後の確認
-- =====================================================================
-- SELECT column_name, data_type, is_nullable FROM information_schema.columns
--  WHERE table_name = 'incidents' ORDER BY ordinal_position;
--  -- reporter_name が NULL 許容（匿名報告で NULL）であること
-- SELECT COUNT(*) FROM incidents;   -- 0 であること
-- SELECT version FROM schema_meta WHERE id = 1;  -- 21 になっていること
